color: null
fieldLayouts:
  e607ac3d-98e2-4400-873a-8abb1007631f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:22:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f9b33196-c07e-4340-a86b-187a1ee9d322
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-24T13:43:37+00:00'
            elementCondition: null
            fieldUid: 1fecbeb4-dfb3-4886-82ce-08ca8ee9cfaa # Nav Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec110366-407e-4c7a-a49d-2d038b6bcb04
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2604514-0eff-4052-9a2b-066bbe8f1ed5
        userCondition: null
handle: Navigation
hasTitleField: true
icon: ''
name: Hauptmen√º
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
