defaultPlacement: end
enableVersioning: true
handle: imprint
name: Impressum
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Prim√§re eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    enabledByDefault: true
    hasUrls: true
    template: _pages/_default.twig
    uriFormat: impressum
type: single
